//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWEB514_Elie_Atamech.BLL.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string email { get; set; }
        public int salary { get; set; }
        public int speciality { get; set; }
        public int hospital { get; set; }
    
        public virtual Hospital Hospital1 { get; set; }
        public virtual Speciality Speciality1 { get; set; }
    }
}
